In [1]:
from wands import RandomData, AdiosWands

#generate Data
data = RandomData([4,5])
print(str(data))

params={
    "IPAddress": "127.0.0.1",
    "Port": "12306",
    "Timeout": "5",
    "TransportMode": "reliable", 
    "RendezvousReaderCount": "1",
}

ads = AdiosWands(link="DeclaredIO1", parameters=params)
ads.send("IO1","testdata", data.get_numpy_array())

[[0.86066052 0.73578664 0.32556862 0.21765915 0.19092748]
 [0.32000445 0.02962106 0.04733892 0.21432003 0.39825942]
 [0.65092408 0.57236069 0.71763534 0.04871704 0.75522951]
 [0.84815202 0.67693125 0.25233169 0.37416321 0.58596066]]
shape in send: (4, 5)
count in send (4, 5)
start in send (0, 0)


In [1]:
from wands import RandomData, AdiosWands
import numpy as np

#generate Data
data = np.arange(20).reshape(4,5)
print(str(data))

params={
    "IPAddress": "127.0.0.1",
    "Port": "12306",
    "Timeout": "5",
    "TransportMode": "reliable", 
    "RendezvousReaderCount": "1",
}

ads = AdiosWands(link="DeclaredIO1", parameters=params)
ads.send("IO1","testdata", data)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
shape in send: (4, 5)
count in send (4, 5)
start in send (0, 0)


In [1]:
#ON CSD3
from wands import AdiosWands
import numpy as np

params={
    "IPAddress": "127.0.0.1",
    "Port": "12306",
    "Timeout": "5",
    "TransportMode": "reliable", 
    "RendezvousReaderCount": "1",
}

ads = AdiosWands(link="Stream_data", parameters=params)
print("adios object created")
file = "/home/stefanie/work/adios/adiosnetwork/data/30420.h5"
#req_var = ['xax/XAX_CHFS/2_PRELOAD','xbt/XBT/CHANNEL16']
req_list = ['/xax/XAX_CHFS/2_PRELOAD']
#req_var = np.ascontiguousarray(req_var)
#req_var = np.array('xax/XAX_CHFS/2_PRELOAD')
print(type(req_list))
#data = ads.request_remote_data(req_data=req_var,data_source=file)
#ads.send(eng_name= "IO1", var_name = "req_data",data=req_list)
data = ads.receive_multiple_datasets(eng_name='IO1',req_data=req_list)
# print(data[0])
# print(data[1])
print(data)
for k in data:
    print(k)



adios object created
<class 'list'>
just got into receive
after open
this data was received [[-0.00780628 -0.00779378 -0.00778128 ...  0.27514654  0.26721197
   0.27026373]
 [ 0.          0.          0.         ...  1.          1.
   1.        ]
 [ 1.          1.          1.         ...  1.          1.
   1.        ]]
[None]
None
